export const navLinks : NavLink[] = [
    {
        title : 'Spot',
        redirect : '/',
        type : 'link'
    },
    {
        title : 'Futures',
        redirect : '/',
        type : 'link'
    },
    {
        title : 'Lend',
        redirect : '/',
        type : 'link'
    },
    {
        title : 'More',
        redirect : '/',
        type : 'dropdown'
    },
]

export const slides = [
  {
    image: '/banners/home-banner-limbo-3.png', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-refer.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-stacked-yield-sol-new.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-stacked-yield-usd.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-usdt-3.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-wct-quest.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  {
    image: '/banners/home-banner-wire-transfers.webp', // Place the image in public/images/
    heading: 'Trade more. Earn more.',
    subheading: 'Earn daily rewards that scale with exchange volume.',
    button: 'View Quests',
  },
  // Add more slide objects here if needed
];

// Dummy Data for dashboard : 

export const newStocks: stockShowProps = {
  title: "New",
  stockData: [
    {
      stockName: "NS",
      curPrice: 0.16087,
      imgUrl: "/icons/ns.webp", 
      status: 0.12,
    },
    {
      stockName: "HAEDAL",
      curPrice: 0.10297,
      imgUrl: "/icons/haedal.webp", 
      status: 3.69,
    },
    {
      stockName: "BLUE",
      curPrice: 0.10263,
      imgUrl: "/icons/blue.webp", 
      status: 0.95,
    },
    {
      stockName: "SEND",
      curPrice: 0.4741,
      imgUrl: "/icons/send.webp", 
      status: -0.57,
    },
    {
      stockName: "DEEP",
      curPrice: 0.14035,
      imgUrl: "/icons/deep.webp", 
      status: 2.57,
    },
  ],
};

export const popularStocks: stockShowProps = {
  title: "Popular",
  stockData: [
    {
      stockName: "ETH",
      curPrice: 2538.48,
      imgUrl: "/icons/eth.webp",
      status: -0.19,
    },
    {
      stockName: "SOL",
      curPrice: 145.67,
      imgUrl: "/icons/sol.webp",
      status: 0.51,
    },
    {
      stockName: "BTC",
      curPrice: 104988.30,
      imgUrl: "/icons/btc.webp",
      status: 0.07,
    },
    {
      stockName: "SUI",
      curPrice: 3.01,
      imgUrl: "/icons/sui.webp",
      status: 0.58,
    },
    {
      stockName: "USDT",
      curPrice: 1.00,
      imgUrl: "/icons/usdt.webp",
      status: -0.01,
    },
  ],
};

export const topGainers: stockShowProps = {
  title: "Top Gainers",
  stockData: [
    {
      stockName: "MELANIA",
      curPrice: 0.271,
      imgUrl: "/icons/melania.webp", // placeholder
      status: 7.97,
    },
    {
      stockName: "ZRO",
      curPrice: 2.07,
      imgUrl: "/icons/zro.svg", // placeholder
      status: 7.84,
    },
    {
      stockName: "TRUMP",
      curPrice: 10.55,
      imgUrl: "/icons/trump.webp", // placeholder
      status: 6.44,
    },
    {
      stockName: "KMNO",
      curPrice: 0.06284,
      imgUrl: "/icons/kmno.webp", // placeholder
      status: 6.02,
    },
    {
      stockName: "WIF",
      curPrice: 0.8545,
      imgUrl: "/icons/wif.webp", // placeholder
      status: 5.74,
    },
  ],
};

export const cryptoList: CryptoData[] = [
  {
    name: "Bitcoin",
    symbol: "BTC/USD",
    price: "$104,718.20",
    volume24h: "$1.7M",
    marketCap: "$2.1T",
    change24h: "-0.30%",
    graph7d: "graph_btc.png",
    imgUrl : "/icons/btc.webp"
  },
  {
    name: "Ethereum",
    symbol: "ETH/USD",
    price: "$2,510.23",
    volume24h: "$11.6M",
    marketCap: "$303.1B",
    change24h: "-0.52%",
    graph7d: "graph_eth.png",
    imgUrl : "/icons/eth.webp"
  },
  {
    name: "USDT",
    symbol: "USDT/USD",
    price: "$1.0004",
    volume24h: "$442.6K",
    marketCap: "$155.5B",
    change24h: "-0.02%",
    graph7d: "graph_usdt.png",
    imgUrl : "/icons/usdt.webp"
  },
  {
    name: "Solana",
    symbol: "SOL/USD",
    price: "$144.13",
    volume24h: "$8.8M",
    marketCap: "$76.1B",
    change24h: "-0.77%",
    graph7d: "graph_sol.png",
    imgUrl : "/icons/sol.webp"
  },
  {
    name: "Sui",
    symbol: "SUI/USD",
    price: "$2.8416",
    volume24h: "$655.6K",
    marketCap: "$9.7B",
    change24h: "-5.76%",
    graph7d: "graph_sui.png",
    imgUrl : "/icons/sui.webp"
  },
  {
    name: "Chainlink",
    symbol: "LINK/USD",
    price: "$12.972",
    volume24h: "$2.3K",
    marketCap: "$8.5B",
    change24h: "-1.62%",
    graph7d: "graph_link.png",
  },
  {
    name: "Shiba Inu",
    symbol: "SHIB/USD",
    price: "$0.00001214",
    volume24h: "$1.2",
    marketCap: "$7.1B",
    change24h: "0.00%",
    graph7d: "graph_shib.png",
  },
  {
    name: "Pepe",
    symbol: "PEPE/USD",
    price: "$0.00001098",
    volume24h: "$7K",
    marketCap: "$4.6B",
    change24h: "-0.43%",
    graph7d: "graph_pepe.png",
  },
  {
    name: "Uniswap",
    symbol: "UNI/USD",
    price: "$7.166",
    volume24h: "$15.1K",
    marketCap: "$4.3B",
    change24h: "-3.18%",
    graph7d: "graph_uni.png",
  },
  {
    name: "Aave",
    symbol: "AAVE/USD",
    price: "$270.57",
    volume24h: "$9.4K",
    marketCap: "$4.1B",
    change24h: "-4.50%",
    graph7d: "graph_aave.png",
  },
  {
    name: "Ondo",
    symbol: "ONDO/USD",
    price: "$0.7938",
    volume24h: "$1.9K",
    marketCap: "$2.5B",
    change24h: "+1.69%",
    graph7d: "graph_ondo.png",
  },
  {
    name: "Official Trump",
    symbol: "TRUMP/USD",
    price: "$9.935",
    volume24h: "$37.3K",
    marketCap: "$2B",
    change24h: "+0.21%",
    graph7d: "graph_trump.png",
  },
   {
    name: "POL (ex-MATIC)",
    symbol: "POL/USD",
    price: "-",
    volume24h: "-",
    marketCap: "$1.8B",
    change24h: "-",
    graph7d: "graph_pol.png",
  },
  {
    name: "Ethena",
    symbol: "ENA/USD",
    price: "$0.2949",
    volume24h: "$5.6K",
    marketCap: "$1.8B",
    change24h: "+1.31%",
    graph7d: "graph_ena.png",
  },
  {
    name: "Render",
    symbol: "RENDER/USD",
    price: "$3.475",
    volume24h: "$4.6",
    marketCap: "$1.7B",
    change24h: "+0.35%",
    graph7d: "graph_rndr.png",
  },
  {
    name: "Worldcoin",
    symbol: "WLD/USD",
    price: "$0.9857",
    volume24h: "$19.7",
    marketCap: "$1.6B",
    change24h: "0.00%",
    graph7d: "graph_wld.png",
  },
  {
    name: "Jupiter",
    symbol: "JUP/USD",
    price: "$0.41",
    volume24h: "$9K",
    marketCap: "$1.2B",
    change24h: "+0.24%",
    graph7d: "graph_jup.png",
  },
  {
    name: "Bonk",
    symbol: "BONK/USD",
    price: "$0.00001463",
    volume24h: "$6.6K",
    marketCap: "$1.1B",
    change24h: "+1.02%",
    graph7d: "graph_bonk.png",
  },
  {
    name: "Dogwifhat",
    symbol: "WIF/USD",
    price: "$0.8522",
    volume24h: "$2.6K",
    marketCap: "$832.4M",
    change24h: "+2.95%",
    graph7d: "graph_wif.png",
  },
  {
    name: "Lido",
    symbol: "LDO/USD",
    price: "$0.8046",
    volume24h: "$3.3K",
    marketCap: "$718.3M",
    change24h: "+0.79%",
    graph7d: "graph_ldo.png",
  },
  {
    name: "Jito",
    symbol: "JTO/USD",
    price: "$1.9281",
    volume24h: "$62.8K",
    marketCap: "$651M",
    change24h: "-0.15%",
    graph7d: "graph_jto.png",
  },
  {
    name: "Walrus",
    symbol: "WAL/USD",
    price: "$0.4455",
    volume24h: "$1.2K",
    marketCap: "$602.5M",
    change24h: "-3.93%",
    graph7d: "graph_wal.png",
  },
  {
    name: "Pudgy Penguins",
    symbol: "PENG/USD",
    price: "$0.00957",
    volume24h: "$6.6K",
    marketCap: "$597.4M",
    change24h: "-0.21%",
    graph7d: "graph_peng.png",
  },
  {
    name: "PYTH",
    symbol: "PYTH/USD",
    price: "$0.1029",
    volume24h: "$5.6K",
    marketCap: "$596.2M",
    change24h: "-2.28%",
    graph7d: "graph_pyth.png",
  },
  {
    name: "Raydium",
    symbol: "RAY/USD",
    price: "$2.0647",
    volume24h: "$37.2",
    marketCap: "$586.4M",
    change24h: "-0.12%",
    graph7d: "graph_ray.png",
  },
  {
    name: "ApeCoin",
    symbol: "APE/USD",
    price: "$0.678",
    volume24h: "$68.2",
    marketCap: "$542.1M",
    change24h: "+0.61%",
    graph7d: "graph_ape.png",
  },
  {
    name: "Helium",
    symbol: "HNT/USD",
    price: "$2.50",
    volume24h: "$2.4K",
    marketCap: "$459M",
    change24h: "+0.28%",
    graph7d: "graph_hnt.png",
  },
  {
    name: "Starknet",
    symbol: "STRK/USD",
    price: "$0.117",
    volume24h: "$1.4K",
    marketCap: "$392.3M",
    change24h: "-0.51%",
    graph7d: "graph_strk.png",
  },
  {
    name: "DeepBook",
    symbol: "DEEP/USD",
    price: "$0.13359",
    volume24h: "$3.3K",
    marketCap: "$335.2M",
    change24h: "-5.03%",
    graph7d: "graph_deep.png",
  },
  {
    name: "Wormhole",
    symbol: "W/USD",
    price: "$0.0669",
    volume24h: "$10.5K",
    marketCap: "$307.6M",
    change24h: "+0.91%",
    graph7d: "graph_wormhole.png",
  },
  {
    name: "cat in a dogs world",
    symbol: "MEW/USD",
    price: "$0.002749",
    volume24h: "$5.4",
    marketCap: "$248.1M",
    change24h: "-2.48%",
    graph7d: "graph_mew.png",
  },
  {
    name: "LayerZero",
    symbol: "ZRO/USD",
    price: "$1.9361",
    volume24h: "$1.3K",
    marketCap: "$214.8M",
    change24h: "-2.94%",
    graph7d: "graph_zro.png",
  },
  {
    name: "Blur",
    symbol: "BLUR/USD",
    price: "-",
    volume24h: "-",
    marketCap: "$188.8M",
    change24h: "-",
    graph7d: "graph_blur.png",
  },
  {
    name: "Moo Deng",
    symbol: "MOODENG/USD",
    price: "$0.15313",
    volume24h: "$2.4K",
    marketCap: "$154.9M",
    change24h: "-5.07%",
    graph7d: "graph_moodeng.png",
  },
  {
    name: "Drift",
    symbol: "DRIFT/USD",
    price: "$0.445",
    volume24h: "$10.2K",
    marketCap: "$138.3M",
    change24h: "-2.92%",
    graph7d: "graph_drift.png",
  },
  {
    name: "Kamino",
    symbol: "KMNO/USD",
    price: "$0.06247",
    volume24h: "$2.1K",
    marketCap: "$130.4M",
    change24h: "+3.31%",
    graph7d: "graph_kmino.png",
  },
  {
    name: "Magic Eden",
    symbol: "ME/USD",
    price: "$0.795",
    volume24h: "$15",
    marketCap: "$119.4M",
    change24h: "0.00%",
    graph7d: "graph_me.png",
  },
  {
    name: "io.net",
    symbol: "IO/USD",
    price: "$0.6734",
    volume24h: "$4.5K",
    marketCap: "$110.7M",
    change24h: "+0.49%",
    graph7d: "graph_ionet.png",
  },
  {
    name: "Book of Meme",
    symbol: "BOME/USD",
    price: "$0.001606",
    volume24h: "$3.2K",
    marketCap: "$110.6M",
    change24h: "+0.94%",
    graph7d: "graph_bome.png",
  },
  {
    name: "Hivemapper",
    symbol: "HONEY/USD",
    price: "-",
    volume24h: "-",
    marketCap: "$106.4M",
    change24h: "-",
    graph7d: "graph_honey.png",
  },
  {
    name: "Melania Meme",
    symbol: "MELANIA/USD",
    price: "$0.268",
    volume24h: "$2.4K",
    marketCap: "$103.6M",
    change24h: "+3.08%",
    graph7d: "graph_melania.png",
  },
  {
    name: "Goatseus Maximus",
    symbol: "GOAT/USD",
    price: "$0.1028",
    volume24h: "$0.1",
    marketCap: "$102M",
    change24h: "0.00%",
    graph7d: "graph_goat.png",
  },
  {
    name: "Sonic SVM",
    symbol: "SONIC/USD",
    price: "$0.21206",
    volume24h: "$627.4",
    marketCap: "$76.4M",
    change24h: "-0.92%",
    graph7d: "graph_sonic.png",
  },
  {
    name: "Act I The AI Prophecy",
    symbol: "ACT/USD",
    price: "$0.0459",
    volume24h: "$1.9K",
    marketCap: "$43.8M",
    change24h: "+1.10%",
    graph7d: "graph_act.png",
  },
  {
    name: "deBridge",
    symbol: "DBR/USD",
    price: "-",
    volume24h: "-",
    marketCap: "$39.8M",
    change24h: "-",
    graph7d: "graph_dbr.png",
  },
  {
    name: "Tensor",
    symbol: "TNSR/USD",
    price: "$0.1123",
    volume24h: "$85.1",
    marketCap: "$37.7M",
    change24h: "-0.27%",
    graph7d: "graph_tnsr.png",
  },
  {
    name: "Suilend",
    symbol: "SEND/USD",
    price: "$0.476",
    volume24h: "$22.8",
    marketCap: "$32.6M",
    change24h: "+1.58%",
    graph7d: "graph_send.png",
  },
  {
    name: "Bluefin",
    symbol: "BLUE/USD",
    price: "$0.09829",
    volume24h: "$374.3",
    marketCap: "$30.2M",
    change24h: "-4.75%",
    graph7d: "graph_blue.png",
  },
  {
    name: "Parcl",
    symbol: "PRCL/USD",
    price: "$0.0762",
    volume24h: "$1.1K",
    marketCap: "$26.7M",
    change24h: "-4.39%",
    graph7d: "graph_prcl.png",
  },
  {
    name: "Helium Mobile",
    symbol: "MOBILE/USD",
    price: "$0.0003025",
    volume24h: "$56.7",
    marketCap: "$25.5M",
    change24h: "0.00%",
    graph7d: "graph_mobile.png",
  },
  {
    name: "Wen",
    symbol: "WEN/USD",
    price: "$0.00003449",
    volume24h: "$16.4K",
    marketCap: "$25.2M",
    change24h: "-0.83%",
    graph7d: "graph_wen.png",
  },
  {
    name: "Jambo",
    symbol: "J/USD",
    price: "$0.1605",
    volume24h: "$1.2K",
    marketCap: "$24.7M",
    change24h: "-6.63%",
    graph7d: "graph_jambo.png",
  },
  {
    name: "Sanctum",
    symbol: "CLOUD/USD",
    price: "$0.1303",
    volume24h: "$36.6K",
    marketCap: "$23.5M",
    change24h: "+0.62%",
    graph7d: "graph_cloud.png",
  },
  {
    name: "SuiNS Token",
    symbol: "NS/USD",
    price: "$0.15068",
    volume24h: "$118.4",
    marketCap: "$23.3M",
    change24h: "-7.03%",
    graph7d: "graph_cloud.png",
  },
  {
    name: "Haedal Protocol",
    symbol: "HAEDAL/USD",
    price: "$0.10242",
    volume24h: "$1.1k",
    marketCap: "$19.7M",
    change24h: "-1.75%",
    graph7d: "graph_cloud.png",
  }
];


